In [1]:
import torch

In [4]:
x = torch.zeros(10, 20, dtype = torch.float64)

In [5]:
x

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
       dtype=torch.float64)

In [65]:
def add_noise_to_embeddings(x, feature_noise_level = 0.0, node_noise_level = 0.0, device = 'cpu'):
  node_mask = torch.rand(x.size(0), device = device) >= 1.0 - node_noise_level
  feature_mask = torch.rand(x.size(1), device = device) >= 1.0 - feature_noise_level
  noise = torch.randn(x.shape, device = device)
  noise = noise * node_mask.view(-1, 1) * feature_mask.view(1, -1)
  return x + noise

In [67]:
add_noise_to_embeddings(torch.zeros(10, 5), feature_noise_level = 0.0, node_noise_level = 0.0)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [84]:
add_noise_to_embeddings(torch.zeros(10, 5), feature_noise_level = 1, node_noise_level = 0.8)

tensor([[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [-0.1278,  1.0095,  1.4943,  1.5964, -0.1076],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [-0.3475, -0.4565, -0.3246,  0.7282,  1.0920],
        [ 0.3180,  1.7468,  1.3427,  0.3229, -1.4050],
        [ 0.2212, -0.0103,  0.5024, -0.7270, -2.0214],
        [ 0.2829,  1.8324,  0.0943,  0.3567, -0.7862],
        [ 0.8415, -1.4660, -1.2863, -1.3390, -1.0384],
        [ 0.3774,  0.3527,  0.4468,  1.0492,  0.5298],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000]])

In [ ]:
# feature_noise_level = 0.25, node_noise_level = 0.25
# feature_noise_level = 0.25, node_noise_level = 0.50
# feature_noise_level = 0.25, node_noise_level = 0.75

# feature_noise_level = 0.50, node_noise_level = 0.25
# feature_noise_level = 0.50, node_noise_level = 0.50
# feature_noise_level = 0.50, node_noise_level = 0.75

# feature_noise_level = 0.75, node_noise_level = 0.25
# feature_noise_level = 0.75, node_noise_level = 0.50
# feature_noise_level = 0.75, node_noise_level = 0.75